package twiddle.dsl

import scala.lms.common._
import java.io.{PrintWriter,StringWriter,FileOutputStream}
import scala.reflect._
import scala.collection.BitSet
import scala.language.higherKinds
import scala.math.pow
import scala.language.implicitConversions

object CodeGen {
  import Syntax._

  type AST[A] = List[Term]
  abstract class Term
  case class IntPtr() extends Term
  case class Const(e: Term) extends Term
  case class Addr(e: Term) extends Term
  case class Var(s: String) extends Term
  case class Num[A](n: A) extends Term
  case class Bool(b: Boolean) extends Term
  case class Assign(v: Var, e: Term) extends Term
  case class Decl(v: Term) extends Term
  case class I(v: Var) extends Term // Integer
  case class F(v: Var) extends Term // Float
  case class D(v: Var) extends Term // Double
  case class Rshift(v: Term, n: Term) extends Term // >>
  case class Minus(v: Term, n: Term) extends Term // -
  case class Plus(v: Term, n: Term) extends Term // +
  case class Times(v: Term, n: Term) extends Term // *
  case class Divide(v: Term, n: Term) extends Term // /
  case class Mod(v: Term, n: Term) extends Term // /
  case class Cast(c: Term, e: Term) extends Term
  case class IfThenElse(cond: Term, conseq: Term, alt: Term) extends Term
  case class Ref(e: Term) extends Term // pointer dereference
  
  implicit object EmitTwiddleAST extends CExp[AST] {
    def num[A](v: A) = List(Num(v))
    def bool(b: Boolean) = List(Bool(b))
    def add[A: Numeric](a: AST[A], b: AST[A]): AST[A] = {
      val List(n1) = a
      val List(n2) = b
      List(Plus(n1, n2))
    }

    def sub[A: Numeric](a: AST[A], b: AST[A]): AST[A] = {
      val List(n1) = a
      val List(n2) = b
      List(Minus(n1, n2))
    }

    def mul[A: Numeric](a: AST[A], b: AST[A]): AST[A] = {
      val List(n1) = a
      val List(n2) = b
      List(Times(n1, n2))
    }

    def div(a: AST[Int], b: AST[Int]): AST[Int] = {
      val List(n1) = a
      val List(n2) = b
      List(Divide(n1, n2))
    }

    def mod(a: AST[Int], b: AST[Int]): AST[Int] = {
      val List(n1) = a
      val List(n2) = b
      List(Mod(n1, n2))
    }

    def ifThenElse_[A] : AST[_] => (() => AST[_]) => (() => AST[_]) => AST[_] =
            b => t => e => (b, t(), e()) match {
              case (List(t0), List(t1), List(t2)) => List(IfThenElse(t0, t1, t2))
            }

    def log2(a: AST[Int]): AST[Int] = {
      val List(t) = a
      List(Decl(F(Var("x0"))),
           Decl(I(Var("x1"))),
           Assign(Var("x0"), t),
           Assign(Var("x1"), Ref(Cast(Const(IntPtr()), Addr(Var("x0"))))),
           Assign(Var("x1"), Minus(Rshift(Var("x1"), Num(23)), Num(127))))
    }
  }

  // TODO: Tagless interpreter for Twiddle AST
  // ? use LMS (eval.scala in LMS tutorial; Ops[T[_]])
  // either eval/pretty print code or generete C code

  def emitGenHeader() = println("// START OF CODE GENERATED BY TWIDDLE")
  def emitGenFooter() = println("// END OF CODE GENERATED BY TWIDDLE")

  // Multi-stage evaluator
  def eval(ast: AST[_]): Unit = {
    ast match {
      case hd::tl => eval_term(hd); eval(tl)
      case _ => ()
    }
  }

  def eval_term(t: Term): Unit = t match {
    case Num(n) => print(n)
    case Bool(b) => if(b) print(1) else print(0)
    case Var(s) => print(s)
    case Decl(e) => e match {
      case F(v) => print("float "); eval_term(v); println(";")
      case I(v) => print("int "); eval_term(v); println(";")
      case D(v) => print("double "); eval_term(v); println(";")
    }
    case Assign(v, e) => eval_term(v); print(" = "); eval_term(e); println(";")
    case Cast(c, v) => print("("); eval_term(c); print(")"); eval_term(v)
    case Const(e) => print("const "); eval_term(e)
    case IntPtr() => print("int* ")
    case Addr(e) => print("&("); eval_term(e); print(")")
    case Minus(a, b) => eval_term(a); print(" - "); eval_term(b)
    case Plus(a, b) => eval_term(a); print(" + "); eval_term(b)
    case IfThenElse(cond, conseq, alt) => print("if("); eval_term(cond); print(") {"); eval_term(conseq); print("} else {"); eval_term(alt); println("}")
    case Rshift(a, b) => print("("); eval_term(a); print(" >> "); eval_term(b); print(")")
    case Ref(e) => print("*("); eval_term(e); print(")")

    case otherwise => println(s"Unknown AST node $otherwise")
  }
}